---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-context7-secrets
  namespace: ai
spec:
  data:
  - secretKey: CONTEXT7_API_KEY
    remoteRef:
      key: apikey_context7_mcp
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
