---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-kubernetes-nas-secrets
  namespace: ai
spec:
  data:
  - secretKey: kubeconfig
    remoteRef:
      key: kubeconfig_nas_mcp
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
