---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-secrets
  namespace: downloaders
spec:
  data:
  - secretKey: wireguard_private_key
    remoteRef:
      key: downloaders_gluetun_wireguard_private_key
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
