---
apiVersion: v1
kind: Service
metadata:
  name: mcp-github
  namespace: ai
  labels:
    app.kubernetes.io/name: mcp-github
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mcp-github
  ports:
  - name: http
    port: 8082
    targetPort: http
    protocol: TCP
