---
apiVersion: v1
kind: Service
metadata:
  name: qui
  namespace: downloaders
  labels:
    app.kubernetes.io/name: qui
spec:
  selector:
    app.kubernetes.io/name: qui
  ports:
  - name: qui
    port: 7476
    targetPort: qui
    protocol: TCP
  type: ClusterIP
