---
apiVersion: v1
kind: Service
metadata:
  name: mcp-playwright
  namespace: ai
  labels:
    app.kubernetes.io/name: mcp-playwright
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mcp-playwright
  ports:
  - name: http
    port: 8931
    targetPort: http
    protocol: TCP
