---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-openwebui-key
  namespace: openwebui
spec:
  data:
  - secretKey: apikey
    remoteRef:
      key: apikey_litellm_openwebui
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
