---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: garage-operator
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/rajsinghtech/charts/garage-operator
  ref:
    tag: 0.7.3
