---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- csi-driver-nfs/
- minio/
- garage/
- longhorn/
- prometheusrule-object-store.yaml

sortOptions:
  order: fifo
