---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
  namespace: logging
spec:
  data:
  - secretKey: endpoint
    remoteRef:
      key: ${loki_s3_endpoint_key}
  - secretKey: access_key_id
    remoteRef:
      key: ${loki_s3_accesskeyid_key}
  - secretKey: secret_key
    remoteRef:
      key: ${loki_s3_secretkey_key}
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
      metadata:
        annotations: {}
        labels: {}
      data:
        loki_s3_endpoint: "{{ .endpoint }}"
        loki_s3_accesskeyid: "{{ .access_key_id }}"
        loki_s3_secretaccesskey: "{{ .secret_key }}"
