---
apiVersion: v1
kind: Service
metadata:
  name: versitygw-inventory
  namespace: versitygw
  labels:
    app.kubernetes.io/name: versitygw-inventory
spec:
  selector:
    app.kubernetes.io/name: versitygw-inventory
  ports:
  - name: metrics
    port: 9103
    targetPort: metrics
