---
apiVersion: v1
kind: Namespace
metadata:
  name: dns
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
---
apiVersion: v1
kind: Namespace
metadata:
  name: freeradius
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
