---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-home-assistant-secrets
  namespace: ai
spec:
  data:
  - secretKey: HOMEASSISTANT_TOKEN
    remoteRef:
      key: homeassistant_token_mcp
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
