---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- oci-repository-garage-operator.yaml
- helm-release-garage-operator.yaml

commonAnnotations:
  # as this is a critical infrastructure component, prevent pruning unintentionally
  kustomize.toolkit.fluxcd.io/prune: disabled
