---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secrets.yaml
- service.yaml
- deployment.yaml
- ingress-s3.yaml
- ingress-web.yaml
- servicemonitor.yaml
- prometheusrule-garage.yaml

commonAnnotations:
  # as this is a critical infrastructure component, prevent pruning unintentionally
  kustomize.toolkit.fluxcd.io/prune: disabled

configMapGenerator:
- name: garage-config
  namespace: garage
  files:
  - conf.d/garage.toml
