---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-credentials
  namespace: garage
spec:
  data:
  - secretKey: admin-token
    remoteRef:
      key: ${garage_admin_token_key}
  - secretKey: rpc-secret
    remoteRef:
      key: ${garage_rpc_secret_key}
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
