---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- litellm/
- mcp-context7/
- mcp-grafana/
- mcp-home-assistant/
- mcp-kubernetes/
- mcp-playwright/
- mcp-unifi-network/
- mcp-unifi-protect/
- openwebui/

sortOptions:
  order: fifo
