---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- network-policy.yaml
- litellm/
- mcp-context7/
- mcp-github/
- mcp-grafana/
- mcp-home-assistant/
- mcp-kubernetes-homelab/
- mcp-kubernetes-nas/
- mcp-kubernetes-sandbox/
- mcp-playwright/
- mcp-unifi-network/
- mcp-unifi-protect/
- n8n/
- obsidian-vault/
- openclaw/
- openwebui/

sortOptions:
  order: fifo
