---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac-loki-query-correctness.yaml
- cronjob-loki-query-correctness.yaml
- prometheusrule-object-store-kpi.yaml

configMapGenerator:
- name: loki-query-correctness-script
  namespace: logging
  files:
  - loki-query-correctness.py
