---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/berriai/litellm-helm
  ref:
    tag: 1.93.0
    digest: sha256:eb4ecbd3c82f9c393c017b73bed7afe6e6cb22002f6793b4173e1d3b711dfa91
