---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: ai
spec:
  data:
  - secretKey: LITELLM_MASTER_KEY
    remoteRef:
      key: litellm_master_key
  - secretKey: LITELLM_SALT_KEY
    remoteRef:
      key: litellm_salt_key
  - secretKey: OPENROUTER_API_KEY
    remoteRef:
      key: apikey_openrouter_litellm
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: litellm_redis_password
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
