---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace-n8n.yaml
- postgres.yaml
- postgres-service.yaml
- secrets.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- servicemonitor.yaml

sortOptions:
  order: fifo
