---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  data:
  - secretKey: N8N_ENCRYPTION_KEY
    remoteRef:
      key: n8n_encryption_key
  - secretKey: N8N_INSTANCE_OWNER_PASSWORD_HASH
    remoteRef:
      key: n8n_owner_password_hash
  - secretKey: N8N_CREDENTIALS_OVERWRITE_DATA
    remoteRef:
      key: n8n_credentials_overwrite
  - secretKey: LITELLM_API_KEY
    remoteRef:
      key: apikey_litellm_n8n
  - secretKey: N8N_SMTP_USER
    remoteRef:
      key: n8n_smtp_user
  - secretKey: N8N_SMTP_PASS
    remoteRef:
      key: n8n_smtp_password
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
