---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
