---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-unifi-network-secrets
  namespace: ai
spec:
  data:
  - secretKey: UNIFI_NETWORK_USERNAME
    remoteRef:
      key: unifi_network_username_mcp
  - secretKey: UNIFI_NETWORK_PASSWORD
    remoteRef:
      key: unifi_network_password_mcp
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
