---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: irrelevant
spec:
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: ${db_name}-backup-store
      serverName: ${db_suffix_current:=default}
