---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-grafana-secrets
  namespace: ai
spec:
  data:
  - secretKey: GRAFANA_URL
    remoteRef:
      key: grafana_url_mcp
  - secretKey: GRAFANA_SERVICE_ACCOUNT_TOKEN
    remoteRef:
      key: grafana_service_account_token_mcp
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
