---
apiVersion: v1
kind: Service
metadata:
  name: mcp-grafana
  namespace: ai
  labels:
    app.kubernetes.io/name: mcp-grafana
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mcp-grafana
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
