---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community-repository
  namespace: flux-system
spec:
  interval: 15m0s
  url: https://grafana-community.github.io/helm-charts
