---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
