---
# yamllint disable rule:line-length
name: test-infrastructure-virtualization

on:
  pull_request:
    paths:
    - '.github/workflows/test-infrastructure-virtualization.yaml'
    - '.github/kind-cluster-single-node.yaml'
    - 'ci/test/infra-virtualization/**'
    - 'infrastructure/subsystems/virtualization-core/**'
    - '!infrastructure/subsystems/virtualization-core/**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-infrastructure-virtualization:
    uses: ppat/github-workflows/.github/workflows/chainsaw-test.yaml@893637588e91e7e531e8d54f07f3ffa468b7b253 # v4.3.0
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      test_path: ./ci/test/infra-virtualization
      chainsaw_config: ./ci/test/chainsaw/.chainsaw.yaml
      kind_config: .github/kind-cluster-single-node.yaml
